<DrawerClickableItem@MDNavigationDrawerItem>
    focus_color: "#e7e4c0"
    text_color: "#4a4939"
    icon_color: "#4a4939"
    ripple_color: "#c5bdd2"
    selected_color: "#0c6c4d"


<DrawerLabelItem@MDNavigationDrawerItem>
    text_color: "#4a4939"
    icon_color: "#4a4939"
    focus_behavior: False
    selected_color: "#4a4939"
    _no_ripple_effect: True

WindowManager:
    Home:

    Modelagem:

    Escolha_M1:
    Monod_MP1:
    Andrews_MP1:
    Levenspinel_MP1:

    Escolha_M2:
    Monod_MP2:
    Andrews_MP2:
    Levenspinel_MP2:

    Escolha_M3:
    Monod_MP3:
    Andrews_MP3:
    Levenspinel_MP3:

    Simulacao:
    Escolha_S1:
    Monod_SP1:
    Andrews_SP1:
    Levenspinel_SP1:

    Escolha_S2:
    Monod_SP2:
    Andrews_SP2:
    Levenspinel_SP2:

    Escolha_S3:
    Monod_SP3:
    Andrews_SP3:
    Levenspinel_SP3:


<Home>:
    name: "home"
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Home"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]

        MDBoxLayout:
            orientation: 'vertical'
            size: root.width, root.height
            MDBoxLayout:
                pos_hint: {'center_x': 0.5, 'top':0.8}
                MDLabel:
                    text: "\n\n\n Bem vindo ao SiMoBio!\n\n\n Este programa realiza simulações e modelagens de processos fermentativos de um modo bem intuitivo! Para isso, basta acessar o menu no canto superior esquerdo da tela e escolher sua função de interesse.\n\n Caso tenha alguma dúvida sobre o embasamento teórico ou de como utilizar o programa corretamente, acesse o site do projeto onde estão dispostos os conceitos teóricos e matemáticos por trás das simulações modelagens, além de um tutorial sobre como realizá-las. Para acessar o site, basta clicar no botão da documentação logo abaixo."
                    halign: 'center'
                    padding_x: 20
        MDBoxLayout:
            orientation: 'horizontal'
            size: root.width, root.height
            MDBoxLayout:
                MDFloatLayout:
                    MDRoundFlatButton:
                        pos_hint: {'center_x': 0.5, 'top':0.8}
                        size_hint_y: 0.15
                        size_hint_x: 0.5
                        height: 30
                        text: 'Documentação'
                        on_release: root.documentacao()

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                source: "logo_simobio5.png"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                #on_press:
                    #app.root.current = "home"
                    #root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Modelagem>:
    name: "modelagem"
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]
            title: "Modelagem"

        MDBoxLayout:
            orientation: 'vertical'
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'top': 1}
                    text: "Qual o tipo de produto do processo?"
                    halign: 'center'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':1.25}
                    text: "Associado ao crescimento"
                    on_release:
                        app.root.current = "Escolha_M1"
                        root.manager.transition.direction = "left"

                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':1.05}
                    text: "Não associado ao crescimento"
                    on_release:
                        app.root.current = "Escolha_M2"
                        root.manager.transition.direction = "left"

                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.85}
                    text: "Parcialmente associado ao crescimento"
                    on_release:
                        app.root.current = "Escolha_M3"
                        root.manager.transition.direction = "left"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                source: "logo_simobio5.png"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                #on_press:
                    #nav_drawer.set_state("close")
                    #app.root.current = "modelagem"
                    #root.manager.transition.direction = "left"

<Escolha_M1>:
    name: "Escolha_M1"
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Modelagem - Produto associado ao crescimento"
        MDBoxLayout:
            orientation: 'vertical'
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'top': 0.8}
                    text: "Qual o modelo cinético de crescimento utilizado no processo?"
                    halign: 'center'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.8}
                    text: "Monod"
                    on_release:
                        app.root.current = "Monod_MP1"
                        root.manager.transition.direction = "left"

                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.4}
                    text: "Andrews"
                    on_release:
                        app.root.current = "Andrews_MP1"
                        root.manager.transition.direction = "left"

                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.0}
                    text: "Levenspiel"
                    on_release:
                        app.root.current = "Levenspinel_MP1"
                        root.manager.transition.direction = "left"

        MDFloatLayout:
            MDRoundFlatButton:
                pos_hint: {'center_x': 0.5, 'top':0.3}
                size_hint_y: 0.15
                size_hint_x: 0.2
                height: 30
                text: 'Voltar'
                on_release:
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "right"

<Monod_MP1>:
    name: "Monod_MP1"
    MDBoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        MDTopAppBar:
            title: "Modelagem - Produto associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]

        MDBoxLayout:
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'center_x': 0.58, 'top':0.4}
                    size_hint_y: 0.25
                    size_hint_x: 0.8
                    height: 30
                    text: 'Escolha um arquivo excel no formato .xlsx correspondente aos dados do processo'
                    halign: 'center'

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatIconButton:
                    pos_hint: {'center_x': 0.5, 'top':0.8}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Carregar arquivo .xlsx'
                    icon: 'folder'
                    on_release: root.show_load()

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.3}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Voltar'
                    on_release:
                        root.limpar_arquivo()
                        root.limpar_caminho()
                        root.reload_f()
                        app.root.current = "Escolha_M1"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                source: "logo_simobio5.png"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Andrews_MP1>:
    name: "Andrews_MP1"
    MDBoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        MDTopAppBar:
            title: "Modelagem - Produto associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]

        MDBoxLayout:
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'center_x': 0.58, 'top':0.4}
                    size_hint_y: 0.25
                    size_hint_x: 0.8
                    height: 30
                    text: 'Escolha um arquivo excel no formato .xlsx correspondente aos dados do processo'
                    halign: 'center'

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatIconButton:
                    pos_hint: {'center_x': 0.5, 'top':0.8}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Carregar arquivo .xlsx'
                    icon: 'folder'
                    on_release: root.show_load()


        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.3}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Voltar'
                    on_release:
                        root.limpar_arquivo()
                        root.limpar_caminho()
                        root.reload_f()
                        app.root.current = "Escolha_M1"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                source: "logo_simobio5.png"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Levenspinel_MP1>:
    name: "Levenspinel_MP1"
    MDBoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        MDTopAppBar:
            title: "Modelagem - Produto associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]

        MDBoxLayout:
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'center_x': 0.58, 'top':0.4}
                    size_hint_y: 0.25
                    size_hint_x: 0.8
                    height: 30
                    text: 'Escolha um arquivo excel no formato .xlsx correspondente aos dados do processo'
                    halign: 'center'

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatIconButton:
                    pos_hint: {'center_x': 0.5, 'top':0.8}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Carregar arquivo .xlsx'
                    icon: 'folder'
                    on_release: root.show_load()

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.3}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Voltar'
                    on_release:
                        root.limpar_arquivo()
                        root.limpar_caminho()
                        root.reload_f()
                        app.root.current = "Escolha_M1"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                source: "logo_simobio5.png"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"


<Escolha_M2>:
    name: "Escolha_M2"
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Modelagem - Produto não associado ao crescimento"
        MDBoxLayout:
            orientation: 'vertical'
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'top': 1}
                    text: "Qual o modelo cinético de crescimento utilizado no processo?"
                    halign: 'center'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.8}
                    text: "Monod"
                    on_release:
                        app.root.current = "Monod_MP2"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.4}
                    text: "Andrews"
                    on_release:
                        app.root.current = "Andrews_MP2"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.0}
                    text: "Levenspiel"
                    on_release:
                        app.root.current = "Levenspinel_MP2"
                        root.manager.transition.direction = "left"
        MDFloatLayout:
            MDRoundFlatButton:
                pos_hint: {'center_x': 0.5, 'top':0.3}
                size_hint_y: 0.25
                size_hint_x: 0.2
                height: 30
                text: 'Voltar'
                on_release:
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "right"

<Monod_MP2>:
    name: "Monod_MP2"
    MDBoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        MDTopAppBar:
            title: "Modelagem - Produto não associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]

        MDBoxLayout:
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'center_x': 0.58, 'top':0.4}
                    size_hint_y: 0.25
                    size_hint_x: 0.8
                    height: 30
                    text: 'Escolha um arquivo excel no formato .xlsx correspondente aos dados do processo'
                    halign: 'center'

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatIconButton:
                    pos_hint: {'center_x': 0.5, 'top':0.8}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Carregar arquivo .xlsx'
                    icon: 'folder'
                    on_release: root.show_load()

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.3}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Voltar'
                    on_release:
                        root.limpar_arquivo()
                        root.limpar_caminho()
                        root.reload_f()
                        app.root.current = "Escolha_M2"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SimoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                source: "logo_simobio5.png"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Andrews_MP2>:
    name: "Andrews_MP2"
    MDBoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        MDTopAppBar:
            title: "Modelagem - Produto não associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]

        MDBoxLayout:
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'center_x': 0.58, 'top':0.4}
                    size_hint_y: 0.25
                    size_hint_x: 0.8
                    height: 30
                    text: 'Escolha um arquivo excel no formato .xlsx correspondente aos dados do processo'
                    halign: 'center'

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatIconButton:
                    pos_hint: {'center_x': 0.5, 'top':0.8}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Carregar arquivo .xlsx'
                    icon: 'folder'
                    on_release: root.show_load()

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.3}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Voltar'
                    on_release:
                        root.limpar_arquivo()
                        root.limpar_caminho()
                        root.reload_f()
                        app.root.current = "Escolha_M2"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                source: "logo_simobio5.png"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")

<Levenspinel_MP2>:
    name: "Levenspinel_MP2"
    MDBoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        MDTopAppBar:
            title: "Modelagem - Produto não associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]

        MDBoxLayout:
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'center_x': 0.58, 'top':0.4}
                    size_hint_y: 0.25
                    size_hint_x: 0.8
                    height: 30
                    text: 'Escolha um arquivo excel no formato .xlsx correspondente aos dados do processo'
                    halign: 'center'

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatIconButton:
                    pos_hint: {'center_x': 0.5, 'top':0.8}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Carregar arquivo .xlsx'
                    icon: 'folder'
                    on_release: root.show_load()

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.3}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Voltar'
                    on_release:
                        root.limpar_arquivo()
                        root.limpar_caminho()
                        root.reload_f()
                        app.root.current = "Escolha_M2"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                source: "logo_simobio5.png"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Escolha_M3>:
    name: "Escolha_M3"
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Modelagem - Produto parcialmente associado ao crescimento"
        MDBoxLayout:
            orientation: 'vertical'
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'top': 1}
                    text: "Qual o modelo cinético de crescimento utilizado no processo?"
                    halign: 'center'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.8}
                    text: "Monod"
                    on_release:
                        app.root.current = "Monod_MP3"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.4}
                    text: "Andrews"
                    on_release:
                        app.root.current = "Andrews_MP3"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.0}
                    text: "Levenspiel"
                    on_release:
                        app.root.current = "Levenspinel_MP3"
                        root.manager.transition.direction = "left"
        MDFloatLayout:
            MDRoundFlatButton:
                pos_hint: {'center_x': 0.5, 'top':0.3}
                size_hint_y: 0.15
                size_hint_x: 0.2
                height: 30
                text: 'Voltar'
                on_release:
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "right"

<Monod_MP3>:
    name: "Monod_MP3"
    MDBoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        MDTopAppBar:
            title: "Modelagem - Produto parcialmente associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]


        MDBoxLayout:
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'center_x': 0.58, 'top':0.4}
                    size_hint_y: 0.25
                    size_hint_x: 0.8
                    height: 30
                    text: 'Escolha um arquivo excel no formato .xlsx correspondente aos dados do processo'
                    halign: 'center'

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatIconButton:
                    pos_hint: {'center_x': 0.5, 'top':0.8}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Carregar arquivo .xlsx'
                    icon: 'folder'
                    on_release: root.show_load()

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.3}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Voltar'
                    on_release:
                        root.limpar_arquivo()
                        root.limpar_caminho()
                        root.reload_f()
                        app.root.current = "Escolha_M3"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"
                source: "logo_simobio5.png"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"

<Andrews_MP3>:
    name: "Andrews_MP3"
    MDBoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        MDTopAppBar:
            title: "Modelagem - Produto parcialmente associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]

        MDBoxLayout:
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'center_x': 0.58, 'top':0.4}
                    size_hint_y: 0.25
                    size_hint_x: 0.8
                    height: 30
                    text: 'Escolha um arquivo excel no formato .xlsx correspondente aos dados do processo'
                    halign: 'center'

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatIconButton:
                    pos_hint: {'center_x': 0.5, 'top':0.8}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Carregar arquivo .xlsx'
                    icon: 'folder'
                    on_release: root.show_load()

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.3}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Voltar'
                    on_release:
                        root.limpar_arquivo()
                        root.limpar_caminho()
                        root.reload_f()
                        app.root.current = "Escolha_M3"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                source: "logo_simobio5.png"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Levenspinel_MP3>:
    name: "Levenspinel_MP3"
    MDBoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        MDTopAppBar:
            title: "Modelagem - Produto parcialmente associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]

        MDBoxLayout:
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'center_x': 0.58, 'top':0.4}
                    size_hint_y: 0.25
                    size_hint_x: 0.8
                    height: 30
                    text: 'Escolha um arquivo excel no formato .xlsx correspondente aos dados do processo'
                    halign: 'center'

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatIconButton:
                    pos_hint: {'center_x': 0.5, 'top':0.8}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Carregar arquivo .xlsx'
                    icon: 'folder'
                    on_release: root.show_load()

        MDBoxLayout:
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.3}
                    size_hint_y: 0.25
                    size_hint_x: 0.2
                    height: 30
                    text: 'Voltar'
                    on_release:
                        root.limpar_arquivo()
                        root.limpar_caminho()
                        root.reload_f()
                        app.root.current = "Escolha_M3"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "SiMoBio"
                spacing: "4dp"
                source: "logo_simobio5.png"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<LoadDialog>:
    MDBoxLayout:
        orientation: 'vertical'
        pos: root.pos
        size: root.size
        FileChooserIconView:
            id: loadfile
            on_selection: root.load(loadfile.path, loadfile.selection), root.cancel()


        MDBoxLayout:
            size_hint_y: 0.08
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint:{'center_x':0.5, 'center_y':0.5}
                    text: "Cancel"
                    on_release: root.cancel()


<ResultDialog1>
    MDBoxLayout:
        id: tabela1
        pos: root.pos
        size: root.size

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.3}
                text: "Modelagem"
                on_press: root.m_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.3, 'center_y':0.3}
                text: "Produtividade"
                on_press: root.m_prod_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.7, 'center_y':0.3}
                text: "Mi"
                on_press: root.m_mi_grafico()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel2()

<ResultDialog2>
    MDBoxLayout:
        id: tabela2
        pos: root.pos
        size: root.size

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.3}
                text: "Modelagem"
                on_press: root.m_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.3, 'center_y':0.3}
                text: "Produtividade"
                on_press: root.m_prod_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.7, 'center_y':0.3}
                text: "Mi"
                on_press: root.m_mi_grafico()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel3()

<ResultDialog3>
    MDBoxLayout:
        id: tabela3
        pos: root.pos
        size: root.size

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.3}
                text: "Modelagem"
                on_press: root.m_grafico()


    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.3, 'center_y':0.3}
                text: "Produtividade"
                on_press: root.m_prod_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.7, 'center_y':0.3}
                text: "Mi"
                on_press: root.m_mi_grafico()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel4()


<ResultDialog_Mod_Andrews1>
    MDBoxLayout:
        id: tabela1
        pos: root.pos
        size: root.size

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.3}
                text: "Modelagem"
                on_press: root.m_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.3, 'center_y':0.3}
                text: "Produtividade"
                on_press: root.m_prod_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.7, 'center_y':0.3}
                text: "Mi"
                on_press: root.m_mi_grafico()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel2()

<ResultDialog_Mod_Andrews2>
    MDBoxLayout:
        id: tabela1
        pos: root.pos
        size: root.size

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.3}
                text: "Modelagem"
                on_press: root.m_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.3, 'center_y':0.3}
                text: "Produtividade"
                on_press: root.m_prod_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.7, 'center_y':0.3}
                text: "Mi"
                on_press: root.m_mi_grafico()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel2()

<ResultDialog_Mod_Andrews3>
    MDBoxLayout:
        id: tabela1
        pos: root.pos
        size: root.size

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.3}
                text: "Modelagem"
                on_press: root.m_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.3, 'center_y':0.3}
                text: "Produtividade"
                on_press: root.m_prod_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.7, 'center_y':0.3}
                text: "Mi"
                on_press: root.m_mi_grafico()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel2()


<ResultDialog_Mod_Levenspinel1>
    MDBoxLayout:
        id: tabela1
        pos: root.pos
        size: root.size

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.3}
                text: "Modelagem"
                on_press: root.m_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.3, 'center_y':0.3}
                text: "Produtividade"
                on_press: root.m_prod_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.7, 'center_y':0.3}
                text: "Mi"
                on_press: root.m_mi_grafico()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel2()

<ResultDialog_Mod_Levenspinel2>
    MDBoxLayout:
        id: tabela1
        pos: root.pos
        size: root.size

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.3}
                text: "Modelagem"
                on_press: root.m_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.3, 'center_y':0.3}
                text: "Produtividade"
                on_press: root.m_prod_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.7, 'center_y':0.3}
                text: "Mi"
                on_press: root.m_mi_grafico()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel2()

<ResultDialog_Mod_Levenspinel3>
    MDBoxLayout:
        id: tabela1
        pos: root.pos
        size: root.size

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.3}
                text: "Modelagem"
                on_press: root.m_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.3, 'center_y':0.3}
                text: "Produtividade"
                on_press: root.m_prod_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.7, 'center_y':0.3}
                text: "Mi"
                on_press: root.m_mi_grafico()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel2()


<Simulacao>:
    name: 'simulacao'
    MDBoxLayout:
        orientation: 'vertical'
        MDBoxLayout:
            orientation: 'vertical'
            MDTopAppBar:
                title: "Simulação"
                left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'top': 1.0}
                    text: "Qual o tipo de produto do processo?"
                    halign: 'center'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':1.25}
                    text: "Associado ao crescimento"
                    on_release:
                        app.root.current = "Escolha_S1"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':1.05}
                    text: "Não associado ao crescimento"
                    on_release:
                        app.root.current = "Escolha_S2"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.85}
                    text: "Parcialmente associado ao crescimento"
                    on_release:
                        app.root.current = "Escolha_S3"
                        root.manager.transition.direction = "left"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"
                source: "logo_simobio5.png"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                #on_press:
                    #nav_drawer.set_state("close")
                    #app.root.current = "simulacao"
                    #root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Escolha_S1>:
    name: "Escolha_S1"
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto associado ao crescimento"
        MDBoxLayout:
            orientation: 'vertical'
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'top': 1}
                    text: "Qual o modelo cinético de crescimento utilizado no processo?"
                    halign: 'center'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.8}
                    text: "Monod"
                    on_release:
                        app.root.current = "Monod_SP1"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.4}
                    text: "Andrews"
                    on_release:
                        app.root.current = "Andrews_SP1"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.0}
                    text: "Levenspiel"
                    on_release:
                        app.root.current = "Levenspinel_SP1"
                        root.manager.transition.direction = "left"
        MDFloatLayout:
            MDRoundFlatButton:
                pos_hint: {'center_x': 0.5, 'top':0.3}
                size_hint_y: 0.15
                size_hint_x: 0.2
                height: 30
                text: 'Voltar'
                on_release:
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "right"

<Monod_SP1>:
    name: 'Monod_SP1'
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]
        MDFloatLayout:
            MDTextField:
                id: t1
                hint_text: "Tempo"
                helper_text: "Tempo em horas de duração do processo"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cx1
                hint_text: "Cxi"
                helper_text: "Concentração inicial de células em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cs1
                hint_text: "Csi"
                helper_text: "Concentração inicial de substrato em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: mimax1
                hint_text: "mimax"
                helper_text: "Velocidade específica máxima de crescimento em 1/h"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ks1
                hint_text: "Ks"
                helper_text: "Constante de substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: yxs1
                hint_text: "Yx/s"
                helper_text: "Razão entre células e substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: kd1
                hint_text: "Kd"
                helper_text: "Constante de morte celular"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: alfa1
                hint_text: "alfa"
                helper_text: "Constante do produto associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}


        MDBoxLayout:
            orientation: 'horizontal'
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.55
                    size_hint_x: 0.3
                    height: 30
                    text: 'Iniciar simulação'
                    on_release: root.p_s1(), root.show_result(), root.reload_f()
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.55
                    size_hint_x: 0.3
                    height: 30
                    text: 'Voltar'
                    on_release:
                        app.root.current = "Escolha_S1"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                source: "logo_simobio5.png"
                padding: "12dp", 0, 0, "56dp"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Andrews_SP1>:
    name: 'Andrews_SP1'
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]
        MDFloatLayout:
            MDTextField:
                id: t1
                hint_text: "Tempo"
                helper_text: "Tempo em horas de duração do processo"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cx1
                hint_text: "Cxi"
                helper_text: "Concentração inicial de células em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cs1
                hint_text: "Csi"
                helper_text: "Concentração inicial de substrato em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: mimax1
                hint_text: "mimax"
                helper_text: "Velocidade específica máxima de crescimento em 1/h"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ks1
                hint_text: "Ks"
                helper_text: "Constante de semi-saturação"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ki1
                hint_text: "Ki"
                helper_text: "Constante de inibição por substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: yxs1
                hint_text: "Yx/s"
                helper_text: "Razão entre células e substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: kd1
                hint_text: "Kd"
                helper_text: "Constante de morte celular"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: alfa1
                hint_text: "alfa"
                helper_text: "Constante do produto associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}


        MDBoxLayout:
            orientation: 'horizontal'
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.55
                    size_hint_x: 0.3
                    height: 30
                    text: 'Iniciar simulação'
                    on_release: root.p_s1(), root.show_result(), root.reload_f()
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.55
                    size_hint_x: 0.3
                    height: 30
                    text: 'Voltar'
                    on_release:
                        app.root.current = "Escolha_S1"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"
                source: "logo_simobio5.png"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")

<Levenspinel_SP1>:
    name: 'Levenspinel_SP1'
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]
        MDFloatLayout:
            MDTextField:
                id: t1
                hint_text: "Tempo"
                helper_text: "Tempo em horas de duração do processo"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cx1
                hint_text: "Cxi"
                helper_text: "Concentração inicial de células em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cs1
                hint_text: "Csi"
                helper_text: "Concentração inicial de substrato em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: mimax1
                hint_text: "mimax"
                helper_text: "Velocidade específica máxima de crescimento em 1/h"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ks1
                hint_text: "Ks"
                helper_text: "Constante de semi-saturação"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: n1
                hint_text: "n"
                helper_text: "parâmetro exponencial"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: yxs1
                hint_text: "Yx/s"
                helper_text: "Razão entre células e substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: kd1
                hint_text: "Kd"
                helper_text: "Constante de morte celular"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: alfa1
                hint_text: "alfa"
                helper_text: "Constante do produto associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cpmax1
                hint_text: "Cpmax"
                helper_text: "Concentração limite do produto"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}

        MDBoxLayout:
            orientation: 'horizontal'
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.55
                    size_hint_x: 0.3
                    height: 30
                    text: 'Iniciar simulação'
                    on_release: root.p_s1(), root.show_result(), root.reload_f()
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.55
                    size_hint_x: 0.3
                    height: 30
                    text: 'Voltar'
                    on_release:
                        app.root.current = "Escolha_S1"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"
                source: "logo_simobio5.png"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Escolha_S2>:
    name: "Escolha_S2"
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto não associado ao crescimento"
        MDBoxLayout:
            orientation: 'vertical'
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'top': 1}
                    text: "Qual o modelo cinético de crescimento utilizado no processo?"
                    halign: 'center'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.8}
                    text: "Monod"
                    on_release:
                        app.root.current = "Monod_SP2"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.4}
                    text: "Andrews"
                    on_release:
                        app.root.current = "Andrews_SP2"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.0}
                    text: "Levenspiel"
                    on_release:
                        app.root.current = "Levenspinel_SP2"
                        root.manager.transition.direction = "left"

        MDFloatLayout:
            MDRoundFlatButton:
                pos_hint: {'center_x': 0.5, 'top':0.3}
                size_hint_y: 0.15
                size_hint_x: 0.2
                height: 30
                text: 'Voltar'
                on_release:
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "right"

<Monod_SP2>:
    name: 'Monod_SP2'
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto não associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]
        MDFloatLayout:
            MDTextField:
                id: t2
                hint_text: "Tempo"
                helper_text: "Tempo em horas de duração do processo"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cx2
                hint_text: "Cxi"
                helper_text: "Concentração inicial de células em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cs2
                hint_text: "Csi"
                helper_text: "Concentração inicial de substrato em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: mimax2
                hint_text: "mimax"
                helper_text: "Velocidade específica máxima de crescimento em 1/h"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ks2
                hint_text: "Ks"
                helper_text: "Constante de substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: yxs2
                hint_text: "Yx/s"
                helper_text: "Razão entre células e substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: kd2
                hint_text: "Kd"
                helper_text: "Constante de morte celular"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: beta2
                hint_text: "beta"
                helper_text: "Constante do produto não associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDBoxLayout:
            orientation: 'horizontal'
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.65
                    size_hint_x: 0.3
                    height: 30
                    text: 'Iniciar simulação'
                    on_release: root.p_s2(), root.show_result(), root.reload_f()
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.65
                    size_hint_x: 0.3
                    height: 30
                    text: 'Voltar'
                    on_release:
                        app.root.current = "Escolha_S2"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"
                source: "logo_simobio5.png"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Andrews_SP2>:
    name: 'Andrews_SP2'
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto não associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]
        MDFloatLayout:
            MDTextField:
                id: t2
                hint_text: "Tempo"
                helper_text: "Tempo em horas de duração do processo"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cx2
                hint_text: "Cxi"
                helper_text: "Concentração inicial de células em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cs2
                hint_text: "Csi"
                helper_text: "Concentração inicial de substrato em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: mimax2
                hint_text: "mimax"
                helper_text: "Velocidade específica máxima de crescimento em 1/h"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ks2
                hint_text: "Ks"
                helper_text: "Constante de semi-saturação"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ki2
                hint_text: "Ki"
                helper_text: "Constante de inibição por substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: yxs2
                hint_text: "Yx/s"
                helper_text: "Razão entre células e substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: kd2
                hint_text: "Kd"
                helper_text: "Constante de morte celular"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: beta2
                hint_text: "beta"
                helper_text: "Constante do produto não associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}

        MDBoxLayout:
            orientation: 'horizontal'
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.65
                    size_hint_x: 0.3
                    height: 30
                    text: 'Iniciar simulação'
                    on_release: root.p_s2(), root.show_result(), root.reload_f()
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.65
                    size_hint_x: 0.3
                    height: 30
                    text: 'Voltar'
                    on_release:
                        app.root.current = "Escolha_S2"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"
                source: "logo_simobio5.png"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"

<Levenspinel_SP2>:
    name: 'Levenspinel_SP2'
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto não associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]

        MDFloatLayout:
            MDTextField:
                id: t2
                hint_text: "Tempo"
                helper_text: "Tempo em horas de duração do processo"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cx2
                hint_text: "Cxi"
                helper_text: "Concentração inicial de células em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cs2
                hint_text: "Csi"
                helper_text: "Concentração inicial de substrato em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: mimax2
                hint_text: "mimax"
                helper_text: "Velocidade específica máxima de crescimento em 1/h"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ks2
                hint_text: "Ks"
                helper_text: "Constante de semi-saturação"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: n2
                hint_text: "n"
                helper_text: "parâmetro exponencial"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: yxs2
                hint_text: "Yx/s"
                helper_text: "Razão entre células e substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: kd2
                hint_text: "Kd"
                helper_text: "Constante de morte celular"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: beta2
                hint_text: "beta"
                helper_text: "Constante do produto não associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cpmax2
                hint_text: "Cpmax"
                helper_text: "Concentração limite de produto"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}

        MDBoxLayout:
            orientation: 'horizontal'
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.65
                    size_hint_x: 0.3
                    height: 30
                    text: 'Iniciar simulação'
                    on_release: root.p_s2(), root.show_result(), root.reload_f()
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.65
                    size_hint_x: 0.3
                    height: 30
                    text: 'Voltar'
                    on_release:
                        app.root.current = "Escolha_S2"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"
                source: "logo_simobio5.png"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Escolha_S3>:
    name: "Escolha_S3"
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto parcialmente associado ao crescimento"
        MDBoxLayout:
            orientation: 'vertical'
            MDFloatLayout:
                MDLabel:
                    pos_hint: {'top': 1}
                    text: "Qual o modelo cinético de crescimento utilizado no processo?"
                    halign: 'center'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.8}
                    text: "Monod"
                    on_release:
                        app.root.current = "Monod_SP3"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.4}
                    text: "Andrews"
                    on_release:
                        app.root.current = "Andrews_SP3"
                        root.manager.transition.direction = "left"
                MDRectangleFlatButton:
                    pos_hint:{'center_x': 0.5, 'top':0.0}
                    text: "Levenspinel"
                    on_release:
                        app.root.current = "Levenspinel_SP3"
                        root.manager.transition.direction = "left"
        MDFloatLayout:
            MDRoundFlatButton:
                pos_hint: {'center_x': 0.5, 'top':0.3}
                size_hint_y: 0.15
                size_hint_x: 0.2
                height: 30
                text: 'Voltar'
                on_release:
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "right"

<Monod_SP3>:
    name: 'Monod_SP3'
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto parcialmente associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]
        MDFloatLayout:
            MDTextField:
                id: t3
                hint_text: "Tempo"
                helper_text: "Tempo em horas de duração do processo"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cx3
                hint_text: "Cxi"
                helper_text: "Concentração inicial de células em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cs3
                hint_text: "Csi"
                helper_text: "Concentração inicial de substrato em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: mimax3
                hint_text: "mimax"
                helper_text: "Velocidade específica máxima de crescimento em 1/h"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ks3
                hint_text: "Ks"
                helper_text: "Constante de substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: yxs3
                hint_text: "Yx/s"
                helper_text: "Razão entre células e substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: kd3
                hint_text: "Kd"
                helper_text: "Constante de morte celular"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: alfa3
                hint_text: "alfa"
                helper_text: "Constante do produto associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: beta3
                hint_text: "beta"
                helper_text: "Constante do produto não associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}

        MDBoxLayout:
            orientation: 'horizontal'
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.65
                    size_hint_x: 0.3
                    height: 30
                    text: 'Iniciar simulação'
                    on_release: root.p_s3(), root.show_result(), root.reload_f()

            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.65
                    size_hint_x: 0.3
                    height: 30
                    text: 'Voltar'
                    on_release:
                        app.root.current = "Escolha_S3"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"
                source: "logo_simobio5.png"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Andrews_SP3>:
    name: 'Andrews_SP3'
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - Produto parcialmente associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]
        MDFloatLayout:
            MDTextField:
                id: t3
                hint_text: "Tempo"
                helper_text: "Tempo em horas de duração do processo"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cx3
                hint_text: "Cxi"
                helper_text: "Concentração inicial de células em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cs3
                hint_text: "Csi"
                helper_text: "Concentração inicial de substrato em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: mimax3
                hint_text: "mimax"
                helper_text: "Velocidade específica máxima de crescimento em 1/h"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ks3
                hint_text: "Ks"
                helper_text: "Constante de semi-saturação"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ki3
                hint_text: "Ki"
                helper_text: "Constante de inibição por substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: yxs3
                hint_text: "Yx/s"
                helper_text: "Razão entre células e substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: kd3
                hint_text: "Kd"
                helper_text: "Constante de morte celular"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: alfa3
                hint_text: "alfa"
                helper_text: "Constante do produto associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: beta3
                hint_text: "beta"
                helper_text: "Constante do produto não associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}

        MDBoxLayout:
            orientation: 'horizontal'
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.65
                    size_hint_x: 0.3
                    height: 30
                    text: 'Iniciar simulação'
                    on_release: root.p_s3(), root.show_result(), root.reload_f()

            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.65
                    size_hint_x: 0.3
                    height: 30
                    text: 'Voltar'
                    on_release:
                        app.root.current = "Escolha_S3"
                        root.manager.transition.direction = "right"
    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"
                source: "logo_simobio5.png"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<Levenspinel_SP3>:
    name: 'Levenspinel_SP3'
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            title: "Simulação - - Produto parcialmente associado ao crescimento"
            left_action_items:[['menu', lambda x: nav_drawer.set_state("open")]]
        MDFloatLayout:
            MDTextField:
                id: t3
                hint_text: "Tempo"
                helper_text: "Tempo em horas de duração do processo"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cx3
                hint_text: "Cxi"
                helper_text: "Concentração inicial de células em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cs3
                hint_text: "Csi"
                helper_text: "Concentração inicial de substrato em g/L"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: mimax3
                hint_text: "mimax"
                helper_text: "Velocidade específica máxima de crescimento em 1/h"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: ks3
                hint_text: "Ks"
                helper_text: "Constante de semi-saturação"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: n3
                hint_text: "n"
                helper_text: "parâmetro exponencial"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: yxs3
                hint_text: "Yx/s"
                helper_text: "Razão entre células e substrato"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: kd3
                hint_text: "Kd"
                helper_text: "Constante de morte celular"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: alfa3
                hint_text: "alfa"
                helper_text: "Constante do produto associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: beta3
                hint_text: "beta"
                helper_text: "Constante do produto não associado ao crescimento"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}
        MDFloatLayout:
            MDTextField:
                id: cpmax3
                hint_text: "Cpmax"
                helper_text: "Concentração limite de produto"
                helper_text_mode: "persistent"
                pos_hint: {"center_x":0.55, "center_y":0.5}

        MDBoxLayout:
            orientation: 'horizontal'
            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.70
                    size_hint_x: 0.3
                    height: 30
                    text: 'Iniciar simulação'
                    on_release: root.p_s3(), root.show_result(), root.reload_f()

            MDFloatLayout:
                MDRoundFlatButton:
                    pos_hint: {'center_x': 0.5, 'top':0.6}
                    size_hint_y: 0.70
                    size_hint_x: 0.3
                    height: 30
                    text: 'Voltar'
                    on_release:
                        app.root.current = "Escolha_S3"
                        root.manager.transition.direction = "right"

    MDNavigationDrawer:
        id: nav_drawer
        radius: (0, 16, 16, 0)
        MDNavigationDrawerMenu:
            MDNavigationDrawerHeader:
                title: "SiMoBio"
                title_color: "#4a4939"
                text: "Menu"
                spacing: "4dp"
                padding: "12dp", 0, 0, "56dp"
                source: "logo_simobio5.png"

            MDNavigationDrawerLabel:
                text: "Onde ir?"

            DrawerClickableItem:
                #icon: "gmail"
                text_right_color: "#4a4939"
                text: "Home"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "home"
                    root.manager.transition.direction = "right"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                #icon: "send"
                text: "Simulação"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "simulacao"
                    root.manager.transition.direction = "left"

            MDNavigationDrawerDivider:

            DrawerClickableItem:
                text: "Modelagem"
                on_press:
                    nav_drawer.set_state("close")
                    app.root.current = "modelagem"
                    root.manager.transition.direction = "left"

<ResultDialog_Sim1>
    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Simulação"
                on_press: root.sim_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Produtividade"
                on_press: root.sim_prod_grafico()

        MDBoxLayout:
            pos: root.pos
            orientation: 'horizontal'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint: {'center_x':0.5, 'center_y':0.6}
                    text: "Mi"
                    on_press: root.sim_mi_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.3}
                text: "Baixar dados"
                on_release: root.save(), root.save_dialog()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel5()

<ResultDialog_Andrews_Sim1>
    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Simulação"
                on_press: root.sim_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Produtividade"
                on_press: root.sim_prod_grafico()

        MDBoxLayout:
            pos: root.pos
            orientation: 'horizontal'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint: {'center_x':0.5, 'center_y':0.6}
                    text: "Mi"
                    on_press: root.sim_mi_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.3}
                text: "Baixar dados"
                on_release: root.save(), root.save_dialog()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel5()

<ResultDialog_Levenspinel_Sim1>
    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Simulação"
                on_press: root.sim_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Produtividade"
                on_press: root.sim_prod_grafico()

        MDBoxLayout:
            pos: root.pos
            orientation: 'horizontal'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint: {'center_x':0.5, 'center_y':0.6}
                    text: "Mi"
                    on_press: root.sim_mi_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.3}
                text: "Baixar dados"
                on_release: root.save(), root.save_dialog()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel5()

<ResultDialog_Sim2>
    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Simulação"
                on_press: root.sim_grafico()


    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Produtividade"
                on_press: root.sim_prod_grafico()

        MDBoxLayout:
            pos: root.pos
            orientation: 'horizontal'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint: {'center_x':0.5, 'center_y':0.6}
                    text: "Mi"
                    on_press: root.sim_mi_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.3}
                text: "Baixar dados"
                on_release: root.save(), root.save_dialog()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel6()

<ResultDialog_Andrews_Sim2>
    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Simulação"
                on_press: root.sim_grafico()


    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Produtividade"
                on_press: root.sim_prod_grafico()

        MDBoxLayout:
            pos: root.pos
            orientation: 'horizontal'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint: {'center_x':0.5, 'center_y':0.6}
                    text: "Mi"
                    on_press: root.sim_mi_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.3}
                text: "Baixar dados"
                on_release: root.save(), root.save_dialog()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel6()

<ResultDialog_Levenspinel_Sim2>
    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Simulação"
                on_press: root.sim_grafico()


    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Produtividade"
                on_press: root.sim_prod_grafico()

        MDBoxLayout:
            pos: root.pos
            orientation: 'horizontal'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint: {'center_x':0.5, 'center_y':0.6}
                    text: "Mi"
                    on_press: root.sim_mi_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.3}
                text: "Baixar dados"
                on_release: root.save(), root.save_dialog()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel6()


<ResultDialog_Sim3>
    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Simulação"
                on_press: root.sim_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Produtividade"
                on_press: root.sim_prod_grafico()

        MDBoxLayout:
            pos: root.pos
            orientation: 'horizontal'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint: {'center_x':0.5, 'center_y':0.6}
                    text: "Mi"
                    on_press: root.sim_mi_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.3}
                text: "Baixar dados"
                on_release: root.save(), root.save_dialog()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel7()

<ResultDialog_Andrews_Sim3>
    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Simulação"
                on_press: root.sim_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Produtividade"
                on_press: root.sim_prod_grafico()

        MDBoxLayout:
            pos: root.pos
            orientation: 'horizontal'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint: {'center_x':0.5, 'center_y':0.6}
                    text: "Mi"
                    on_press: root.sim_mi_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.3}
                text: "Baixar dados"
                on_release: root.save(), root.save_dialog()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel7()

<ResultDialog_Levenspinel_Sim3>
    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Simulação"
                on_press: root.sim_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint: {'center_x':0.5, 'center_y':0.6}
                text: "Produtividade"
                on_press: root.sim_prod_grafico()

        MDBoxLayout:
            pos: root.pos
            orientation: 'horizontal'
            MDFloatLayout:
                MDRectangleFlatButton:
                    pos_hint: {'center_x':0.5, 'center_y':0.6}
                    text: "Mi"
                    on_press: root.sim_mi_grafico()

    MDBoxLayout:
        pos: root.pos
        orientation: 'horizontal'
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.3}
                text: "Baixar dados"
                on_release: root.save(), root.save_dialog()

    MDBoxLayout:
        size_hint_y: 0.08
        pos: root.pos
        MDFloatLayout:
            MDRectangleFlatButton:
                pos_hint:{'center_x':0.5, 'center_y':0.2}
                text: "Voltar"
                on_release: root.cancel7()